# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-25 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20190623_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
